using System;
using System.IO;
using System.Text;
using WinSW.Gui.Model;

namespace WinSW.Gui.Services
{
    /// <summary>
    /// Packages a service for a machine without the GUI: the wrapper, the configuration and
    /// a PowerShell script that installs and starts it.
    /// </summary>
    public static class InstallScriptExporter
    {
        /// <returns>The path of the generated script.</returns>
        public static string Export(ServiceEntry entry, string targetDirectory)
        {
            if (entry.ConfigPath is null)
            {
                throw new InvalidOperationException("The service has no configuration file.");
            }

            Directory.CreateDirectory(targetDirectory);

            string wrapperName = Path.GetFileName(entry.WrapperPath);
            string configName = Path.GetFileName(entry.ConfigPath);

            File.Copy(entry.WrapperPath, Path.Combine(targetDirectory, wrapperName), overwrite: true);
            File.Copy(entry.ConfigPath, Path.Combine(targetDirectory, configName), overwrite: true);

            string script = Path.Combine(targetDirectory, "install.ps1");
            File.WriteAllText(script, Script(entry.ServiceName, wrapperName, configName), new UTF8Encoding(true));
            return script;
        }

        private static string Script(string serviceId, string wrapperName, string configName) => $@"#Requires -RunAsAdministrator
<#
  Installs the '{serviceId}' service with WinSW.
  Generated by WinSW GUI on {DateTime.Now:yyyy-MM-dd}.

  Usage:  .\install.ps1 [-Uninstall] [-NoStart]
  Run from the folder that contains {wrapperName} and {configName}.
#>
param(
    [switch] $Uninstall,
    [switch] $NoStart
)

$ErrorActionPreference = 'Stop'
$here    = Split-Path -Parent $MyInvocation.MyCommand.Path
$wrapper = Join-Path $here '{wrapperName}'
$config  = Join-Path $here '{configName}'

if (-not (Test-Path $wrapper)) {{ throw ""Wrapper not found: $wrapper"" }}
if (-not (Test-Path $config))  {{ throw ""Configuration not found: $config"" }}

function Invoke-WinSW([string] $command) {{
    & $wrapper $command $config --no-elevate
    if ($LASTEXITCODE -ne 0) {{ throw ""winsw $command failed with exit code $LASTEXITCODE"" }}
}}

if ($Uninstall) {{
    try {{ Invoke-WinSW stop }} catch {{ Write-Warning $_ }}
    Invoke-WinSW uninstall
    Write-Host ""Service '{serviceId}' removed.""
    return
}}

Invoke-WinSW install
if (-not $NoStart) {{ Invoke-WinSW start }}
& $wrapper status $config
";
    }
}
